from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from typing import Any


class ErrorCode(StrEnum):
    CALIB_INSUFFICIENT_POSES = "CALIB_INSUFFICIENT_POSES"
    CALIB_RMS_REJECTED = "CALIB_RMS_REJECTED"
    PROFILE_HASH_MISMATCH = "PROFILE_HASH_MISMATCH"
    IMAGE_SIZE_MISMATCH = "IMAGE_SIZE_MISMATCH"
    ARUCO_INSUFFICIENT_MARKERS = "ARUCO_INSUFFICIENT_MARKERS"
    SESSION_RESIDUAL_REJECTED = "SESSION_RESIDUAL_REJECTED"
    RECTIFY_GSD_MISMATCH = "RECTIFY_GSD_MISMATCH"
    LIDAR_DIVERGENCE_WARNING = "LIDAR_DIVERGENCE_WARNING"
    WEIGHTS_MISSING = "WEIGHTS_MISSING"
    MODEL_UNAVAILABLE = "MODEL_UNAVAILABLE"
    LICENSE_NOT_APPROVED = "LICENSE_NOT_APPROVED"
    MASK_EMPTY = "MASK_EMPTY"
    MASK_BORDER_TOUCH = "MASK_BORDER_TOUCH"
    MASK_AREA_RANGE = "MASK_AREA_RANGE"
    MASK_MULTICOMPONENT = "MASK_MULTICOMPONENT"
    POLYGON_INVALID = "POLYGON_INVALID"
    POLYGON_MULTIPOLYGON = "POLYGON_MULTIPOLYGON"
    POLYGON_AREA_RATIO = "POLYGON_AREA_RATIO"
    POLYGON_VERTEX_COUNT = "POLYGON_VERTEX_COUNT"


@dataclass(slots=True)
class PetraError(Exception):
    code: ErrorCode
    message: str
    details: dict[str, Any] | None = None

    def __str__(self) -> str:
        return f"{self.code}: {self.message}"
